name: update build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
        with:
          persist-credentials: false

      - name: Install Packages
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: prod-deploy
          FOLDER: build
          CLEAN: true
